name: KGMAO Production Deployment
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploying KGMAO via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: srv1319.hstgr.io
          username: u633695266
          password: Kalide@123
          port: 65002
          script: |
            source $HOME/.bashrc
            cd /home/u633695266/domains/kgmao.com/public_html/.builds/last-source
            echo "Current Path: $(pwd)"
            echo "Pulling latest code..."
            git fetch https://kalide009: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@github.com/Kalide099/Kalide-GMAO.git main
            git reset --hard FETCH_HEAD

            echo "Installing backend dependencies..."
            npm install

            echo "Installing frontend dependencies & building Vite..."
            cd frontend
            npm install
            npm run build
            cd ..

            echo "Restarting Node.js PM2 process..."
            npx pm2 reload ecosystem.config.js --update-env
            npx pm2 status

            echo "Deployment completed successfully!"

            echo "Deployment completed successfully!"
